# .github/workflows/cd-selfhosted.yml
name: CD → Deploy on Self-Hosted Runner

on:
  workflow_run:
    workflows: ['CI → Build & Publish Docker Image']
    types: 
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # self-hosted 러너가 설치된 머신 레이블
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          cd ~/moodiary
          docker-compose pull
          docker-compose up -d --remove-orphans
