name: CD - Deploy to Self-Hosted Runner

on:
  workflow_run:
    # CI 워크플로 이름을 정확히 그대로 적어야 합니다.
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    # self-hosted 러너 라벨(기본값만) 지정
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove old container (if any)
        run: docker rm -f nginx-proxy || true

      - name: Pull latest image
        run: docker pull hyukie/songdo:latest

      - name: Run container
        run: |
          docker run -d \
            --name nginx-proxy \
            -p 8080:80 \
            hyukie/songdo:latest

      - name: Deployment complete
        run: echo "✅ Deployed hyukie/songdo:latest"
